### ISSUE TITLE
Copy everything in docker

### ISSUE THREAD

**Issue by domoritz** [vega/editor#194]
https://github.com/vega/editor/blob/3ce79722329af7a962940878f84252b71d4e3590/Dockerfile#L11

@andrewshawcare why do we copy everything here when we copied data above?

**Comment by andrewshawcare** [comment]
That line is part of a convention that supports how caching works in Docker. Every line in a `Dockerfile` creates an intermediate image and each intermediate image is cached. This allows Docker to save time by using cached intermediate images for commands that would not change the resultant image. For example:

```
COPY package.json yarn.lock ./
```

For this command, Docker would use the cache, if available, unless the `package.json` or `yarn.lock` files have changed (i.e. have a different checksum since the last build). The normal process for node images is:

```
COPY package.json yarn.lock ./
RUN yarn
COPY . .
```

Which ensures that the first two statements would be able to use the cache on the next build if the package.json or yarn.lock files have not changed. It is important to note that Docker assumes that RUN commands are without side-effects and only invalidates them if previous commands have invalidated the cache or if you force the issue by supplying the `--no-cache` argument to your image build command.

The only change required for this project is that the yarn command depends on some additional folders. I've made an attempt to only copy the necessary folders to limit the likelihood of a cache invalidation before running `yarn`.
