### ISSUE TITLE
tab creates two app containers

### ISSUE THREAD

**Issue by domoritz** [vega/editor#25]
Press tab while not focused on the editor:

![editor](https://user-images.githubusercontent.com/589034/36408210-ed2e0626-15b8-11e8-8a23-4e992ad50f4b.gif)

**Comment by domoritz** [comment]
CC @saurabh0402 @zhirzh

**Comment by zhirzh** [comment]
This happens because `<Route path='/' component={...} />` is rendered at each route starting with `/`. A simple fix is to use the [`exact`](https://reacttraining.com/react-router/web/api/Route/exact-bool) argument. A better solution is use `exact` in conjunction with [`<Switch />`](https://reacttraining.com/react-router/web/api/Switch).

**Comment by zhirzh** [comment]
Submitted a [PR](https://github.com/vega/editor/pull/27)
