### ISSUE TITLE
Export modal has serious UI design problems

### ISSUE THREAD

**Issue by jheer** [vega/editor#338]
I see that the export modal has been updated. Unfortunately, the result is a serious deterioration of the design, with over-large buttons and confusing layout. Text descriptions that should be provided by tooltips or details-on-demand are included as button text. I also recommend splitting the JSON download into separate Vega and Vega-Lite download buttons (as warranted), not a non-standard radio selection _within_ a button.

Finally there is both a PDF button and contradictory text below suggesting a different approach to PDF generation. The extra text should be removed or streamlined to note that it is an alternative PDF generation approach.

![image](https://user-images.githubusercontent.com/202799/55926040-900d0200-5bc4-11e9-932a-bd904b8b9c41.png)

**Comment by ganeshpatro321** [comment]
This should be fixed in #337
There was a problem in importing the styles.
@jheer

**Comment by domoritz** [comment]
I just made another release so this should be fixed. 

I still want the text about the PDF download for now since the PDF export is experimental. 

How strongly do you feel about the radio in the JSON button now that the styles are correct again?

<img width="1399" alt="Screen Shot 2019-04-10 at 23 01 35" src="https://user-images.githubusercontent.com/589034/55934228-c8bcd380-5be4-11e9-9374-fad6e943c069.png">

**Comment by domoritz** [comment]
I'm closing this issue for now but we can still adjust the UI.
