### ISSUE TITLE
Sharing visualizations

### ISSUE THREAD

**Issue by domoritz** [vega/editor#49]
See https://docs.google.com/document/d/1YKBzT-aTrKGxA-G6ktzRSIC-ihc3JCWmNW5k7OL85nA/edit#heading=h.h1iauva9hmtp and look at https://twitter.com/mathisonian/status/973628667854123009 for an idea of what this could be like. 

@mathisonian might have some suggestions for how we can implement this.

**Comment by mathisonian** [comment]
For Idyll's editor I use the following architecture:

`documentation website <-----> idyll api server <--------> amazon DynamoDB`

DynamoDB is a nice backend because it allows you to persist blobs of JSON without really worrying about too much beyond providing auth keys. 

The Idyll API server acts as a proxy to DynamoDB, allowing users the editor frontend to "save" by sending a POST request, and allowing the documentation site code to function without keys to the database. This provides some nice separation of concerns, and you can implement logic like rate limiting, etc on the api server. 

I'm using [now](https://zeit.co/now) to host the API server, its a nice managed environment for node.js code. I also power the documentation site with next.js and now, which gives a way to do dynamic URL routing with react apps, making URLs like https://idyll-lang.org/editor/5b2c7b11-22fb-4e69-98d9-de79a37e7f8d/view possible.

**Comment by domoritz** [comment]
Thanks for the notes! I suppose for the storage any key-value store will work but it's great to hear that dynamo works well for this case. Can you share the server code?

**Comment by mathisonian** [comment]
Yes - happy to share though its not cleaned up for github yet. Will post here once it is open source. The code itself is very simple though, essentially an express.js based proxy to the datastore

**Comment by domoritz** [comment]
* [ ] Set up an oauth server with https://zeit.co/now
* [ ] Support anonymous sharing via spec in the URL
* [ ] Add login dialog
* [ ] Save to gist if the user is logged in
* [ ] Save specs to elastic so that we can search them

Code to look at https://github.com/enjalot/blockbuilder and https://github.com/vega/vega-editor/tree/saveInGist

**Comment by domoritz** [comment]
Works now
